### ISSUE TITLE
original upstream moved to GitLab and being updated

### ISSUE THREAD

**Issue by BrianInglis** [ThomasDickey/esctest2#1]
Original upstream moved to [GitLab](https://gitlab.freedesktop.org/terminal-wg/esctest) and being updated.
Also Terminal Working Group [Specifications](https://gitlab.freedesktop.org/terminal-wg/specifications) where content is under *branch*`/proposals/`... so far.

**Comment by ThomasDickey** [comment]
That's a dead upstream.

**Comment by ThomasDickey** [comment]
It hasn't had significant change for 3 years; iTerm2 hasn't run successfully with esctest for longer than that.
